(()=>{const root=document.getElementById('portalCinematic'),skip=document.getElementById('cinematicSkip'),replay=document.getElementById('cinematicReplay');if(!root||!skip)return;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let timers=[],animations=[],priorFocus=null;
const seen=()=>{try{return sessionStorage.getItem('portal-cinematic-seen')==='1'}catch{return false}};const markSeen=()=>{try{sessionStorage.setItem('portal-cinematic-seen','1')}catch{}};
const clear=()=>{timers.forEach(clearTimeout);timers=[];animations.forEach(item=>{try{item.cancel()}catch{}});animations=[]};const animate=(el,frames,options)=>{if(!el)return;animations.push(el.animate(frames,options))};
function ensureVisuals(){let stage=root.querySelector('.portal-visual-stage');if(stage)return stage;stage=document.createElement('div');stage.className='portal-visual-stage';stage.setAttribute('aria-hidden','true');stage.innerHTML='<div class="portal-picture picture-signal"><i></i><i></i><i></i></div><div class="portal-picture picture-void"><i></i><i></i><i></i></div><div class="portal-picture picture-return"><i></i><i></i><i></i></div><div class="portal-picture picture-real"><i></i><i></i><i></i><i></i></div><div class="portal-mark">PTL↻</div>';root.append(stage);const copy=root.querySelector('.cinematic-copy');if(copy){copy.hidden=true;copy.setAttribute('aria-hidden','true')}const index=root.querySelector('.cinematic-index');if(index)index.hidden=true;root.setAttribute('aria-label','A visual opening: a signal disappears, returns, and becomes real');return stage}
function premium(duration){const stage=ensureVisuals(),aperture=root.querySelector('.cinematic-aperture'),noise=root.querySelector('.cinematic-noise'),pictures=[...stage.querySelectorAll('.portal-picture')],mark=stage.querySelector('.portal-mark');
if(reduced){pictures.forEach((p,i)=>p.style.opacity=i===3?'1':'0');animate(mark,[{opacity:0},{opacity:1}],{duration:900,delay:450,fill:'both'});return}
animate(root,[{filter:'brightness(.05)'},{filter:'brightness(1.25)',offset:.08},{filter:'brightness(.86)',offset:.72},{filter:'brightness(.72)'}],{duration,fill:'both'});
animate(aperture,[{transform:'scale(.02) rotate(-70deg)',opacity:0},{transform:'scale(.3) rotate(-20deg)',opacity:.5,offset:.2},{transform:'scale(1.12) rotate(21deg)',opacity:1,offset:.74},{transform:'scale(.86) rotate(3deg)',opacity:.3}],{duration,fill:'both',easing:'cubic-bezier(.14,.78,.2,1)'});
animate(noise,[{transform:'translate(0,0)'},{transform:'translate(-3%,2%)'},{transform:'translate(2%,-3%)'},{transform:'translate(-1%,1%)'}],{duration:460,iterations:Infinity});
const starts=[350,2350,4350,6350];pictures.forEach((picture,index)=>{animate(picture,[{opacity:0,transform:'scale(1.18) translate3d(0,2%,0)',filter:'blur(13px) saturate(.7)'},{opacity:1,transform:'scale(1.02) translate3d(0,0,0)',filter:'blur(0) saturate(1.2)',offset:.24},{opacity:1,transform:'scale(1) translate3d(0,-1%,0)',filter:'blur(0) saturate(1.05)',offset:.72},{opacity:0,transform:'scale(.94) translate3d(0,-3%,0)',filter:'blur(8px) saturate(.7)'}],{duration:2300,delay:starts[index],fill:'both',easing:'cubic-bezier(.16,.8,.22,1)'})});
animate(mark,[{opacity:0,transform:'scale(.5) rotate(-8deg)',filter:'blur(14px)'},{opacity:1,transform:'scale(1.08)',filter:'blur(0)',offset:.58},{opacity:1,transform:'scale(1)',filter:'blur(0)'}],{duration:2100,delay:8050,fill:'both',easing:'cubic-bezier(.16,.8,.22,1)'});
}
function close(){timers.forEach(clearTimeout);timers=[];root.classList.remove('is-running','is-active');root.setAttribute('aria-hidden','true');document.body.classList.remove('cinematic-locked');markSeen();setTimeout(()=>{root.hidden=true;priorFocus?.focus?.()},850)}
function open(){clear();priorFocus=document.activeElement;root.hidden=false;root.setAttribute('aria-hidden','false');document.body.classList.add('cinematic-locked');requestAnimationFrame(()=>{root.classList.add('is-active','is-running');skip.focus();premium(reduced?1800:10400)});timers.push(setTimeout(close,reduced?2200:11200))}
skip.addEventListener('click',close);replay?.addEventListener('click',open);document.addEventListener('keydown',event=>{if(event.key==='Escape'&&root.classList.contains('is-active'))close()});ensureVisuals();if(!seen())open();
})();