const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list=v=>Array.isArray(v)?v:[];
fetch('/api/living',{cache:'no-store'}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}).then(d=>{
  if(!d.result||!d.cognition||!Array.isArray(d.generations))throw Error('Incomplete living response');
  const s=d.experiment_summary||{};
  $('state').textContent=`${d.version} · ${d.generation_mode}${d.generation_model?' · '+d.generation_model:''} · ${d.generations.length} GENERATIONS · ${d.cognition.readiness} · REAL-WORLD AUTHORITY BLOCKED`;
  $('summary').textContent=`${s.total||0} experiments · ${list(s.extinctions).length} extinctions · ${s.fossils||0} fossils · ${list(s.surprise_branches).length} surprise branches · ${list(s.rebirths).length} controlled rebirths`;

  $('generations').innerHTML=d.generations.map(g=>`<section class="section gen"><h2>Generation ${g.generation}</h2><p class="tag">PARETO ${list(g.frontier).map(esc).join(' · ')||'NONE'} · FOSSILS ${g.fossil_count||0} · EXTINCT ${list(g.extinct).map(esc).join(' · ')||'NONE'} · SURPRISE ${list(g.surprises).map(esc).join(' · ')||'NONE'} · REBORN ${list(g.reborn).map(esc).join(' · ')||'NONE'}</p><div class="grid">${list(g.population).map(h=>`<article class="card lineage ${String(h.id).includes('SURPRISE')?'surprise':''} ${h.state==='REBORN'?'reborn':''} ${h.state==='DEAD'?'dead':''}"><p class="tag">${esc(h.state)} · ${esc(h.niche||'UNNICHED')} · ${esc(h.epistemic_class)}</p><h3>${esc(h.id)}</h3><p>${esc(h.statement)}</p><div class="meter"><i style="width:${Math.round((Number(h.confidence)||0)*100)}%"></i></div><p><b>Confidence</b> ${Math.round((Number(h.confidence)||0)*100)}%</p><p><b>Parents</b> ${list(h.ancestry?.parent_ids).map(esc).join(' + ')||'none'}</p><p><b>Operator</b> ${list(h.ancestry?.operators).map(esc).join(' + ')||'none'}</p><p><b>Prediction</b> ${esc(list(h.predictions)[0]||'none declared')}</p><p><b>Falsifier</b> ${esc(list(h.falsifiers)[0]||'none declared')}</p><p><b>Hard kill</b> ${esc(list(h.hard_kill_conditions)[0]||'none declared')}</p>${h.discriminating_test?`<p><b>Discriminating test</b> ${esc(h.discriminating_test)}</p>`:''}</article>`).join('')}</div><h3>Selection pressure</h3>${list(g.experiments).map(e=>`<p class="outcome ${e.state==='DEAD'?'extinct':''}">${esc(e.candidate_id)} → ${esc(e.outcome?.polarity||'UNKNOWN')} · ${Math.round((Number(e.confidence)||0)*100)}%${e.fossil_risk?` · fossil risk ${Math.round(e.fossil_risk*100)}% from ${list(e.fossil_matches).map(esc).join(', ')}`:''}</p>`).join('')||'<p class="muted">No experiment records.</p>'}</section>`).join('');

  const c=d.cognition;
  $('meta').innerHTML=`<p class="tag">METACOGNITION</p><p>Uncertainty ${Math.round((Number(c.metacognition?.uncertainty)||0)*100)}%</p><p>${esc(c.metacognition?.question||'No question generated.')}</p><p class="tag">REAL-WORLD ACTION ${c.metacognition?.should_act?'ALLOWED':'BLOCKED'}</p>`;
  const trace=c.tool_trace||{budget:{spent:0,limit:0},events:[]};
  $('tools').innerHTML=`<p class="tag">VERIFIED TOOL TRACE · BUDGET ${Number(trace.budget.spent||0).toFixed(2)} / ${Number(trace.budget.limit||0).toFixed(2)}</p>${list(trace.events).map(t=>`<p><b>${esc(t.tool_id)}</b> · ${esc(t.status)} · COST ${esc(t.cost)}<br><span class="trace">${esc(t.output?.provenance||'NO OUTPUT PROVENANCE')}</span></p>`).join('')||'<p>No tool executed.</p>'}`;
  $('critics').innerHTML=`<p class="tag">ACTIVE CRITICS</p>${list(c.critics).slice(0,6).map(q=>`<p>${esc(list(q.attacks)[0]||q.objective||q.id)}</p>`).join('')||'<p>No critic active.</p>'}`;
  $('communication').innerHTML=`<p class="tag">CALIBRATED COMMUNICATION</p><h3>${esc(c.communication?.headline||'No defensible explanation survived.')}</h3><p>${Math.round((Number(c.communication?.confidence)||0)*100)}% confidence · ${Math.round((Number(c.communication?.uncertainty)||0)*100)}% uncertainty · ${esc(c.communication?.epistemic_class||'CONSTRUCTED')}</p><p><b>Falsifier</b> ${esc(c.communication?.falsifier||'none declared')}</p><p><b>Next observation</b> ${esc(c.communication?.next_observation||'none declared')}</p><p class="muted">${esc(c.communication?.caveat||'')}</p>`;
  $('plan').innerHTML=`<p class="tag">PLAN / REPLAN</p>${list(c.plan).map(p=>`<p><b>${esc(p.step)} · ${esc(p.status)}</b><br>${esc(p.detail)}</p>`).join('')||'<p>No plan trace.</p>'}<p class="tag">DECISIVE GATE · ${esc(c.decisive_gate||'UNKNOWN')}</p>`;

  $('timeline').innerHTML=list(d.result.timeline).map(t=>`<li><b>${esc(t.label)}</b> — ${list(t.population).map(h=>`${esc(h.id)} ${Math.round((Number(h.confidence)||0)*100)}% ${esc(h.state)}`).join(' · ')}</li>`).join('')||'<li>No deterministic evidence events.</li>';
  $('fossils').innerHTML=list(d.result.fossil_record).map(f=>`<article class="card fossil"><p class="tag">${esc(f.id)} · DEAD</p><h3>${esc(f.statement)}</h3><p>Final confidence ${Math.round((Number(f.final_confidence)||0)*100)}%</p><p><b>Superseded by</b> ${esc(f.superseded_by||'none')}</p><p><b>Falsifier</b> ${esc(list(f.falsifiers)[0]||'none')}</p><p class="trace">Evidence: ${list(f.evidence).map(e=>esc(e.id)).join(' → ')||'none'}</p></article>`).join('')||'<p>No deterministic fossils yet.</p>';
  $('acceptance').innerHTML=Object.entries({...d.result.acceptance,...c.acceptance}).map(([k,v])=>`<p class="${v?'pass':'blocked'}">${v?'PASS':'PENDING'} · ${esc(k.replaceAll('_',' '))}</p>`).join('');
  $('safety').innerHTML=Object.entries(d.safety||{}).map(([k,v])=>`<p class="${v?'':'blocked'}">${v?'ALLOWED':'BLOCKED'} · ${esc(k.replaceAll('_',' '))}</p>`).join('')||'<p class="blocked">Safety envelope unavailable.</p>';
}).catch(e=>{$('state').textContent='SANDBOX UNAVAILABLE · '+e.message});
