import { strict as assert } from 'node:assert';
import { hybridSearch, contradictions, buildWorldModel, expandGraphNeighborhood } from '../src/lib/semantic-world-model.js';
import { cosine } from '../lib/semantic-embeddings.js';
const nodes=[{id:'a',type:'claim',title:'sensor fusion predicts aquarium risk',provenance:['p1'],evidence_level:'E2'},{id:'b',type:'evidence',title:'sensor trial found no early warning',provenance:['p2'],evidence_level:'E2'}];
assert.equal(hybridSearch('aquarium sensor risk',nodes)[0].node.id,'a');
assert.equal(contradictions(nodes,[{source:'b',target:'a',type:'contradicts',provenance:['p2']}]).length,1);
assert.equal(buildWorldModel({nodes,edges:[{source:'b',target:'a',type:'contradicts'}]}).contradictions.length,1);
const semantic=hybridSearch('unrelated',nodes,{semanticScorer:(_query,node)=>node.id==='b'?.99:.01});
assert.equal(semantic[0].node.id,'b');
const expanded=expandGraphNeighborhood([{node:nodes[0],score:1}],{nodes,edges:[{source:'a',target:'b',type:'related_to'}]});
assert.deepEqual(expanded.map(item=>item.node.id),['a','b']);
assert.equal(cosine([1,0],[1,0]),1);assert.equal(cosine([1,0],[0,1]),0);
