const tokens=s=>new Set(String(s||'').toLowerCase().split(/\W+/).filter(x=>x.length>4));
function similarity(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let hit=0;for(const x of A)if(B.has(x))hit++;return hit/Math.max(A.size,B.size)}
export class FossilMemory {
  constructor(){this.fossils=[]}
  bury(candidate,reason,generation){this.fossils.push({id:`FOSSIL-${candidate.id}`,hypothesis_id:candidate.id,generation,statement:candidate.statement,assumptions:candidate.assumptions||[],falsifiers:candidate.falsifiers||[],reason,evidence:candidate.evidence||[],ancestry:candidate.ancestry})}
  familyRisk(candidate){const matches=this.fossils.map(f=>({...f,similarity:similarity(candidate.statement,f.statement)})).filter(x=>x.similarity>=.28).sort((a,b)=>b.similarity-a.similarity);return{risk:Math.min(.75,matches.reduce((n,x)=>n+x.similarity*.18,0)),matches:matches.slice(0,4)}}
  canRebirth(fossil,newEvidence=[],changedAssumptions=[]){if(!fossil)return{allowed:false,reason:'missing fossil'};if(!newEvidence.length)return{allowed:false,reason:'rebirth requires new evidence'};if(!changedAssumptions.length)return{allowed:false,reason:'rebirth requires an explicitly changed assumption'};return{allowed:true,reason:'new evidence plus changed assumptions justify controlled reconsideration'}}
  rebirth(fossil,newEvidence,changedAssumptions,generation){const gate=this.canRebirth(fossil,newEvidence,changedAssumptions);if(!gate.allowed)return null;return{id:`${fossil.hypothesis_id}-REBORN-G${generation}`,generation,statement:fossil.statement,niche:'SCIENTIST',epistemic_class:'INFERRED',state:'REBORN',confidence:.22,ancestry:{parent_ids:[fossil.hypothesis_id],operators:['REBIRTH']},evidence:newEvidence,assumptions:changedAssumptions,predictions:['The revised assumptions should produce a discriminating outcome absent in the extinct lineage.'],falsifiers:fossil.falsifiers.length?fossil.falsifiers:['New evidence fails to reproduce under the revised assumptions.'],hard_kill_conditions:['The original failure pattern repeats after the changed assumption is controlled.'],discriminating_test:'Repeat the decisive ancestral falsification test while controlling the explicitly changed assumption.',fitness:{accuracy:.3,evidence:.35,novelty:.45,utility:.55,robustness:.45,efficiency:.45,calibration:.7,constraint_compliance:1},history:[{at:`GENERATION_${generation}_REBIRTH`,event:'REBORN_FROM_FOSSIL',confidence:.22,state:'REBORN'}]}}
}
export function applyFossilPenalty(population,fossils){return population.map(h=>{const {risk,matches}=fossils.familyRisk(h);if(!risk)return{...h,fossil_risk:0,fossil_matches:[]};return{...h,confidence:Math.max(0,h.confidence-risk*.2),fitness:{...h.fitness,robustness:Math.max(0,h.fitness.robustness-risk*.25),calibration:Math.min(1,h.fitness.calibration+risk*.08)},fossil_risk:risk,fossil_matches:matches.map(x=>x.hypothesis_id)}})}
