import crypto from 'node:crypto';
import {saveArtifact,hasDatabase} from '../lib/db.js';

const SYSTEM = `You are the curator of The Portal — an archive of strange, forgotten, and imagined objects that anticipated futures before they arrived.
Generate exactly one ORIGINAL catalogue artifact. It should feel discovered rather than invented: materially specific, historically plausible in texture, and evocative. Range freely from 1750–2005 unless the requested mode narrows the search. Never use a real named copyrighted fictional work, character, franchise, or direct imitation.
Prioritize surprise and diversity across era, geography, medium, social class, purpose, condition, and provenance. Include tactile physical evidence. Avoid generic science-fiction language and familiar clichés.
The artifact must imply a future-facing idea and classify what became of that idea. Its modern descendant is a conceptual lineage, not a claim of direct causation. Concepts must be short graph-ready nouns or noun phrases. The unresolved question must be haunting rather than a classroom prompt and begin with What if, Why did, How did, Who, or Where.
Return only the requested structured artifact data.`;
const TYPES=['PRINTED EPHEMERA','FORGOTTEN TECHNOLOGY','IMAGINED WORLD','LOST INVENTION','DOMESTIC OBJECT','INDUSTRIAL PROTOTYPE','SPECIMEN — UNCLASSIFIED','EXHIBIT FROM THE STACKS'];
const STATUSES=['ARRIVED','PARTIALLY ARRIVED','FAILED','ABANDONED','TOO EARLY','STILL WAITING'];
const MODES={wander:'Open an unexpected drawer. Maximize surprise.',arrived:'Find an artifact whose underlying future later ARRIVED or PARTIALLY ARRIVED.',failed:'Find an ambitious future that FAILED or was ABANDONED. Make the failure illuminating.',early:'Find an idea that was TOO EARLY for its infrastructure, economics, materials, or culture.',waiting:'Find a compelling future that is STILL WAITING.',distant:'Find a surprising artifact from 1750–1939 that feels uncannily relevant now.'};
const SCHEMA={type:'object',additionalProperties:false,properties:{era:{type:'string'},year:{type:'integer',minimum:1750,maximum:2005},type:{type:'string',enum:TYPES},title:{type:'string'},description:{type:'string'},provenance:{type:'string'},condition:{type:'integer',minimum:1,maximum:5},imagined_future:{type:'string'},problem:{type:'string'},status:{type:'string',enum:STATUSES},modern_descendant:{type:'string'},concepts:{type:'array',items:{type:'string'},minItems:2,maxItems:5},question:{type:'string'}},required:['era','year','type','title','description','provenance','condition','imagined_future','problem','status','modern_descendant','concepts','question']};
const buckets=globalThis.__portalBuckets||(globalThis.__portalBuckets=new Map()),WINDOW_MS=3600000,MAX_PER_WINDOW=12;
function clientIp(req){return String(req.headers['x-forwarded-for']||req.headers['x-real-ip']||'unknown').split(',')[0].trim()}
function allowed(ip){const now=Date.now(),b=buckets.get(ip);if(!b||now-b.start>=WINDOW_MS){buckets.set(ip,{start:now,count:1});return{ok:true,left:MAX_PER_WINDOW-1}}if(b.count>=MAX_PER_WINDOW)return{ok:false,left:0,retry:Math.ceil((WINDOW_MS-(now-b.start))/1000)};b.count++;return{ok:true,left:MAX_PER_WINDOW-b.count}}
function normalize(s){return String(s||'').trim().replace(/\s+/g,' ')}
function canonicalize(a,mode){const basis=[a.year,normalize(a.title).toLowerCase(),normalize(a.description).toLowerCase(),normalize(a.imagined_future).toLowerCase()].join('|'),fp=crypto.createHash('sha256').update(basis).digest('hex').slice(0,10).toUpperCase();return{...a,id:`PTL-${a.year}-${fp}`,mode,schema_version:3,created_at:new Date().toISOString(),concepts:[...new Set((a.concepts||[]).map(normalize).filter(Boolean))]}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');if(req.method!=='POST'){res.setHeader('Allow','POST');return res.status(405).json({error:'Method not allowed'})}if(!process.env.OPENAI_API_KEY)return res.status(503).json({error:'Archive not configured'});const limit=allowed(clientIp(req));res.setHeader('X-RateLimit-Limit',String(MAX_PER_WINDOW));res.setHeader('X-RateLimit-Remaining',String(limit.left));if(!limit.ok){res.setHeader('Retry-After',String(limit.retry));return res.status(429).json({error:'The archive needs time to settle. Try again later.'})}const mode=typeof req.body?.mode==='string'&&MODES[req.body.mode]?req.body.mode:'wander',controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json',Authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:'gpt-5.6-luna',instructions:SYSTEM,input:`CURATOR MODE: ${mode.toUpperCase()}\n${MODES[mode]}\nCatalogue one artifact unlike an obvious science-fiction cliché.`,max_output_tokens:1200,text:{format:{type:'json_schema',name:'portal_artifact_v3',strict:true,schema:SCHEMA}}})});if(!response.ok){const body=await response.text();console.error('OpenAI status',response.status,body.slice(0,500));return res.status(502).json({error:'Archive upstream unavailable'})}const data=await response.json(),text=(data.output||[]).filter(i=>i.type==='message').flatMap(i=>i.content||[]).filter(i=>i.type==='output_text').map(i=>i.text||'').join('').trim();if(!text)throw new Error('OpenAI returned no artifact text');const artifact=canonicalize(JSON.parse(text),mode);if(hasDatabase()){try{await saveArtifact(artifact);artifact.persistence='shared'}catch(e){console.error('archive persistence error',e?.message||e);artifact.persistence='local-fallback'}}else artifact.persistence='local';return res.status(200).json(artifact)}catch(error){console.error('artifact error',error?.name||error?.message||error);return res.status(error?.name==='AbortError'?504:500).json({error:error?.name==='AbortError'?'Archive timed out':'Archive failure'})}finally{clearTimeout(timer)}}
