import crypto from 'node:crypto';
import {saveArtifact,hasDatabase,findArtifacts} from '../lib/db.js';
const SYSTEM=`You curate The Portal, an archive of futures. Generate one original catalogue artifact with historically plausible texture. You are creating an AI-curated discovery object, not asserting verified history. Clearly separate observed/plausible description from conceptual inference. Never fabricate a URL or citation. sources must therefore be an empty array unless genuine source URLs were supplied in the prompt. relationships describe conceptual relationships, not proven causation. Return only structured data.`;
const TYPES=['PRINTED EPHEMERA','FORGOTTEN TECHNOLOGY','IMAGINED WORLD','LOST INVENTION','DOMESTIC OBJECT','INDUSTRIAL PROTOTYPE','SPECIMEN — UNCLASSIFIED','EXHIBIT FROM THE STACKS'],STATUSES=['ARRIVED','PARTIALLY ARRIVED','FAILED','ABANDONED','TOO EARLY','STILL WAITING'];
const MODES={wander:'Maximize surprise and conceptual distance from ordinary technology history.',arrived:'Underlying future later ARRIVED or PARTIALLY ARRIVED.',failed:'Ambitious future FAILED or was ABANDONED.',early:'Idea was TOO EARLY for its infrastructure, economics, materials, or culture.',waiting:'Compelling future is STILL WAITING.',distant:'1750–1939 and uncannily relevant now.'};
const relationship={type:'object',additionalProperties:false,properties:{type:{type:'string',enum:['PRECEDED_BY','ECHOED_BY','FAILED_BECAUSE','BECAME_POSSIBLE_WHEN']},label:{type:'string'}},required:['type','label']};
const SCHEMA={type:'object',additionalProperties:false,properties:{era:{type:'string'},year:{type:'integer',minimum:1750,maximum:2005},type:{type:'string',enum:TYPES},title:{type:'string'},description:{type:'string'},provenance:{type:'string'},condition:{type:'integer',minimum:1,maximum:5},imagined_future:{type:'string'},problem:{type:'string'},status:{type:'string',enum:STATUSES},modern_descendant:{type:'string'},concepts:{type:'array',items:{type:'string'},minItems:2,maxItems:5},question:{type:'string'},evidence_level:{type:'string',enum:['AI-CURATED','CONCEPTUAL-INFERENCE']},sources:{type:'array',items:{type:'object',additionalProperties:false,properties:{title:{type:'string'},url:{type:'string'}},required:['title','url']},maxItems:4},relationships:{type:'array',items:relationship,maxItems:4}},required:['era','year','type','title','description','provenance','condition','imagined_future','problem','status','modern_descendant','concepts','question','evidence_level','sources','relationships']};
const buckets=globalThis.__portalBuckets||(globalThis.__portalBuckets=new Map()),WINDOW_MS=3600000,MAX_PER_WINDOW=12;
function ip(req){return String(req.headers['x-forwarded-for']||req.headers['x-real-ip']||'unknown').split(',')[0].trim()}function allowed(k){const now=Date.now(),b=buckets.get(k);if(!b||now-b.start>=WINDOW_MS){buckets.set(k,{start:now,count:1});return true}if(b.count>=MAX_PER_WINDOW)return false;b.count++;return true}function norm(s){return String(s||'').trim().replace(/\s+/g,' ')}
function canonical(a,mode){const fp=crypto.createHash('sha256').update([a.year,norm(a.title).toLowerCase(),norm(a.description).toLowerCase()].join('|')).digest('hex').slice(0,10).toUpperCase();return{...a,id:`PTL-${a.year}-${fp}`,mode,schema_version:4,created_at:new Date().toISOString(),concepts:[...new Set((a.concepts||[]).map(norm).filter(Boolean))],sources:(a.sources||[]).filter(x=>/^https:\/\//.test(x.url||''))}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json; charset=utf-8');if(req.method!=='POST'){res.setHeader('Allow','POST');return res.status(405).json({error:'Method not allowed'})}if(!process.env.OPENAI_API_KEY)return res.status(503).json({error:'Archive not configured'});if(!allowed(ip(req)))return res.status(429).json({error:'The archive needs time to settle. Try again later.'});const mode=MODES[req.body?.mode]?req.body.mode:'wander';let context='';if(hasDatabase()){try{const recent=await findArtifacts({limit:8});context='\nRECENT TITLES TO AVOID RESEMBLING: '+recent.map(x=>`${x.year} ${x.title} [${(x.concepts||[]).join(', ')}]`).join(' | ')}catch{}}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json',Authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:'gpt-5.6-luna',instructions:SYSTEM,input:`CURATOR MODE: ${mode.toUpperCase()}\n${MODES[mode]}${context}`,max_output_tokens:1500,text:{format:{type:'json_schema',name:'portal_artifact_v4',strict:true,schema:SCHEMA}}})});if(!r.ok)return res.status(502).json({error:'Archive upstream unavailable'});const data=await r.json(),text=(data.output||[]).flatMap(i=>i.content||[]).filter(i=>i.type==='output_text').map(i=>i.text||'').join('').trim();if(!text)throw new Error('No artifact');const a=canonical(JSON.parse(text),mode);if(hasDatabase()){try{await saveArtifact(a);a.persistence='shared'}catch(e){console.error('persistence',e?.message);a.persistence='local-fallback'}}else a.persistence='local';return res.status(200).json(a)}catch(e){return res.status(e?.name==='AbortError'?504:500).json({error:e?.name==='AbortError'?'Archive timed out':'Archive failure'})}finally{clearTimeout(timer)}}
